import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});
const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<LayoutProps<"/">>) {
  return (
    <html lang="en">
      <body
        className={
          `${interSans.variable} ${poppinsSans.variable} antialiased` +
          "bg-bg text-body"
        }
      >
        {props.children}
      </body>
    </html>
  );
}
